server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:bkms
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
       enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE